# Generated by Django 6.0.4 on 2026-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
