# Generated by Django 6.0.4 on 2026-06-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_description_service_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description_ar',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
    ]
